// Generated by gencpp from file act_map_exp/PlanConfigResponse.msg
// DO NOT EDIT!


#ifndef ACT_MAP_EXP_MESSAGE_PLANCONFIGRESPONSE_H
#define ACT_MAP_EXP_MESSAGE_PLANCONFIGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace act_map_exp
{
template <class ContainerAllocator>
struct PlanConfigResponse_
{
  typedef PlanConfigResponse_<ContainerAllocator> Type;

  PlanConfigResponse_()
    {
    }
  PlanConfigResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::act_map_exp::PlanConfigResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::act_map_exp::PlanConfigResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PlanConfigResponse_

typedef ::act_map_exp::PlanConfigResponse_<std::allocator<void> > PlanConfigResponse;

typedef boost::shared_ptr< ::act_map_exp::PlanConfigResponse > PlanConfigResponsePtr;
typedef boost::shared_ptr< ::act_map_exp::PlanConfigResponse const> PlanConfigResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::act_map_exp::PlanConfigResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::act_map_exp::PlanConfigResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace act_map_exp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::act_map_exp::PlanConfigResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::act_map_exp::PlanConfigResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::act_map_exp::PlanConfigResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::act_map_exp::PlanConfigResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::act_map_exp::PlanConfigResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::act_map_exp::PlanConfigResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::act_map_exp::PlanConfigResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::act_map_exp::PlanConfigResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::act_map_exp::PlanConfigResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "act_map_exp/PlanConfigResponse";
  }

  static const char* value(const ::act_map_exp::PlanConfigResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::act_map_exp::PlanConfigResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::act_map_exp::PlanConfigResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::act_map_exp::PlanConfigResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanConfigResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::act_map_exp::PlanConfigResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::act_map_exp::PlanConfigResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ACT_MAP_EXP_MESSAGE_PLANCONFIGRESPONSE_H
