// Generated by gencpp from file act_map_exp/PlanConfig.msg
// DO NOT EDIT!


#ifndef ACT_MAP_EXP_MESSAGE_PLANCONFIG_H
#define ACT_MAP_EXP_MESSAGE_PLANCONFIG_H

#include <ros/service_traits.h>


#include <act_map_exp/PlanConfigRequest.h>
#include <act_map_exp/PlanConfigResponse.h>


namespace act_map_exp
{

struct PlanConfig
{

typedef PlanConfigRequest Request;
typedef PlanConfigResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlanConfig
} // namespace act_map_exp


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::act_map_exp::PlanConfig > {
  static const char* value()
  {
    return "b3532af339db184b4a6a974d00ee4fe6";
  }

  static const char* value(const ::act_map_exp::PlanConfig&) { return value(); }
};

template<>
struct DataType< ::act_map_exp::PlanConfig > {
  static const char* value()
  {
    return "act_map_exp/PlanConfig";
  }

  static const char* value(const ::act_map_exp::PlanConfig&) { return value(); }
};


// service_traits::MD5Sum< ::act_map_exp::PlanConfigRequest> should match
// service_traits::MD5Sum< ::act_map_exp::PlanConfig >
template<>
struct MD5Sum< ::act_map_exp::PlanConfigRequest>
{
  static const char* value()
  {
    return MD5Sum< ::act_map_exp::PlanConfig >::value();
  }
  static const char* value(const ::act_map_exp::PlanConfigRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::act_map_exp::PlanConfigRequest> should match
// service_traits::DataType< ::act_map_exp::PlanConfig >
template<>
struct DataType< ::act_map_exp::PlanConfigRequest>
{
  static const char* value()
  {
    return DataType< ::act_map_exp::PlanConfig >::value();
  }
  static const char* value(const ::act_map_exp::PlanConfigRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::act_map_exp::PlanConfigResponse> should match
// service_traits::MD5Sum< ::act_map_exp::PlanConfig >
template<>
struct MD5Sum< ::act_map_exp::PlanConfigResponse>
{
  static const char* value()
  {
    return MD5Sum< ::act_map_exp::PlanConfig >::value();
  }
  static const char* value(const ::act_map_exp::PlanConfigResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::act_map_exp::PlanConfigResponse> should match
// service_traits::DataType< ::act_map_exp::PlanConfig >
template<>
struct DataType< ::act_map_exp::PlanConfigResponse>
{
  static const char* value()
  {
    return DataType< ::act_map_exp::PlanConfig >::value();
  }
  static const char* value(const ::act_map_exp::PlanConfigResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACT_MAP_EXP_MESSAGE_PLANCONFIG_H
