// Generated by gencpp from file act_map_exp/PlanConfigRequest.msg
// DO NOT EDIT!


#ifndef ACT_MAP_EXP_MESSAGE_PLANCONFIGREQUEST_H
#define ACT_MAP_EXP_MESSAGE_PLANCONFIGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace act_map_exp
{
template <class ContainerAllocator>
struct PlanConfigRequest_
{
  typedef PlanConfigRequest_<ContainerAllocator> Type;

  PlanConfigRequest_()
    : config()  {
    }
  PlanConfigRequest_(const ContainerAllocator& _alloc)
    : config(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _config_type;
  _config_type config;





  typedef boost::shared_ptr< ::act_map_exp::PlanConfigRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::act_map_exp::PlanConfigRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlanConfigRequest_

typedef ::act_map_exp::PlanConfigRequest_<std::allocator<void> > PlanConfigRequest;

typedef boost::shared_ptr< ::act_map_exp::PlanConfigRequest > PlanConfigRequestPtr;
typedef boost::shared_ptr< ::act_map_exp::PlanConfigRequest const> PlanConfigRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::act_map_exp::PlanConfigRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::act_map_exp::PlanConfigRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::act_map_exp::PlanConfigRequest_<ContainerAllocator1> & lhs, const ::act_map_exp::PlanConfigRequest_<ContainerAllocator2> & rhs)
{
  return lhs.config == rhs.config;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::act_map_exp::PlanConfigRequest_<ContainerAllocator1> & lhs, const ::act_map_exp::PlanConfigRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace act_map_exp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::act_map_exp::PlanConfigRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::act_map_exp::PlanConfigRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::act_map_exp::PlanConfigRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::act_map_exp::PlanConfigRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::act_map_exp::PlanConfigRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::act_map_exp::PlanConfigRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::act_map_exp::PlanConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3532af339db184b4a6a974d00ee4fe6";
  }

  static const char* value(const ::act_map_exp::PlanConfigRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3532af339db184bULL;
  static const uint64_t static_value2 = 0x4a6a974d00ee4fe6ULL;
};

template<class ContainerAllocator>
struct DataType< ::act_map_exp::PlanConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "act_map_exp/PlanConfigRequest";
  }

  static const char* value(const ::act_map_exp::PlanConfigRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::act_map_exp::PlanConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string config\n"
;
  }

  static const char* value(const ::act_map_exp::PlanConfigRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::act_map_exp::PlanConfigRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.config);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanConfigRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::act_map_exp::PlanConfigRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::act_map_exp::PlanConfigRequest_<ContainerAllocator>& v)
  {
    s << indent << "config: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.config);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACT_MAP_EXP_MESSAGE_PLANCONFIGREQUEST_H
